repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: ruff-format
        name: Format code with Ruff
        entry: just fmt
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-lint
        name: Lint code with Ruff
        entry: just lint
        language: system
        types: [python]
        pass_filenames: false

      - id: pyright
        name: Run type checking with pyright
        entry: just typecheck
        language: system
        types: [python]
        pass_filenames: false

      - id: pytest
        name: Run tests with pytest
        entry: just test
        language: system
        types: [python]
        pass_filenames: false
